---
- name: Create a Folder on vSphere
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_hostname: ""
    vcenter_username: ""
    vcenter_password: ""
    datacenter_name: ""
    sample_vm_folder: ""
    vm_folder_type: "" # datastore, host, network, vm (default)
    vm_folder_state: "" # present=create, absent=destroy.S

  tasks:
  - name: Create a VM folder on given datacenter
    vcenter_folder:
      hostname: "{{ VMWARE_HOST }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      datacenter: "{{ datacenter_name }}"
      folder_name: "{{ sample_vm_folder }}"
      folder_type: "{{ vm_folder_type }}"
      state: "{{ vm_folder_state }}"
    register: vm_folder_creation_result
    delegate_to: localhost