---
- name: Create VM from scratch for a demo
  hosts: localhost
  become: false
  gather_facts: false
 # collections:
 #   - community.vmware
 # pre_tasks:
 #     - include_vars: vars.yml
  tasks:
      - name: Deploy a virtual machine in a datastore different from the datastore of the template
        community.vmware.vmware_guest:
  #        hostname: "{{ vcenter_hostname }}"
  #        username: "{{ vcenter_username }}"
  #        password: "{{ vcenter_password }}"
  #        name: "{{ vm_name }}"
          name: "MyVM_RHEL_test"
          state: present
  #        template: "{{ template_name }}"
          template: "rhel86-tpl"
          # Here datastore can be different which holds template
          #datastore: "{{ virtual_machine_datastore }}"
          datastore: "WorkloadDatastore"
          hardware:
            memory_mb: 512
            num_cpus: 2
            scsi: paravirtual
        delegate_to: localhost