---
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: ''
    vcenter_username: ''
    vcenter_password: ''
    datacenter_name: ''
    vcenter_moid: ''
    vcenter_schema: ''

  tasks:
  - name: Gather some information about a guest using MoID.
    vmware_guest_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      moid: "{{ vcenter_moid }}"
      schema: "{{ vcenter_schema }}"
      properties: ["config.hardware.memoryMB", "guest.disk", "overallStatus"]
    delegate_to: localhost
    register: vm_moid_info